config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pokemons, only: [:index, :show] 
  	
  # Watch out for several or nested routes
  resources :users, only: [:show, :index] do
  	resources :user_pokemons, only: [:new, :create, :destroy]
  end

  resources :battles, only: [:new, :create, :show]

  get '/landing', to: 'pages#landing', as: 'landing'
  get '/home', to: 'pages#home', as: 'home'
end


# Rails.application.routes.draw do
#   devise_for :users
#   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#   resources :pokemons, only: [:index, :show] do
#     resources :user_pokemons, only: [:new, :create]
#   end    
#   # Watch out for several or nested routes

#   get '/landing', to: 'pages#home', as: 'landing'
#   root to: 'pages#profile'
# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/battle.rb
class Battle < ApplicationRecord
  belongs_to :user
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  has_many :user_pokemons, dependent: :destroy
  has_many :users, through: :user_pokemons

  serialize :moves

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [:name, :kind_of, :move],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
  has_many :user_pokemons
  has_many :battles, dependent: :destroy
  has_many :pokemons, through: :user_pokemons
  validates :user_pokemons, length: { maximum: 3 }

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [:username],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user_pokemon.rb
class UserPokemon < ApplicationRecord
  belongs_to :user
  belongs_to :pokemon
  validates_associated :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :photo])
  end

  # [...]
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def after_sign_in_path_for(resource)
    user_path(current_user) # your path
  end
end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController
  def new
    @battle = Battle.new
    @enemy = User.find(params[:enemy_id])
    authorize @battle
  end

  def create
    @enemy = User.find(params[:battle][:enemy_id])

    @battle = Battle.new(user: current_user, enemy_id: @enemy.id)

    @user = current_user

    authorize @battle

    if @battle.save
      redirect_to battle_path(@battle, pokemon_id: params[:battle][:pokemon_id])
    else
      render :new
    end
  end

  def show
    @battle = Battle.find(params[:id])

    authorize @battle
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:landing, :home]

  def landing
    @disable_nav = true
  end

  def home
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    if params[:query].present?
      @pokemons = policy_scope(Pokemon).global_search(params[:query])
    else
      @pokemons = policy_scope(Pokemon).paginate(page: params[:page]).per_page(20)
    end
    authorize @pokemons
  end

  def show
    @pokemon = Pokemon.find(params[:id])
    authorize @pokemon
  end
end

app/controllers/user_pokemons_controller.rb
class UserPokemonsController < ApplicationController
  def new
    @user_pokemon = UserPokemon.new
    authorize @user_pokemon
  end

  def create
    @user_pokemon = UserPokemon.new(user_pokemon_params)

    authorize @user_pokemon

    @user_pokemon.user = current_user
    if @user_pokemon.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def destroy
    @user_pokemon = UserPokemon.find(params[:id])

    authorize @user_pokemon

    if @user_pokemon.delete
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  private

  def user_pokemon_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:user_pokemon).permit(:user_id, :pokemon_id, :nickname)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @users = policy_scope(User)
    if params[:sort]
      if params[:sort] == "rank_desc"
        @users = policy_scope(User).sort_by { |u| -u.energy }
      elsif params[:sort] == "rank_asc"
        @users = policy_scope(User).sort_by { |u| u.energy }
      end
    elsif params[:query]
      @users = policy_scope(User).global_search(params[:query])
    end
  end

  def show
    authorize @user
  end

  private

  def set_user
    if current_user
      @user = User.find(params[:id])
    else
      redirect_to landing_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/battles/final_message.html.erb
<h1>test</h1>

app/views/battles/new.html.erb
<h1 class="username mt-3">Hello <%= current_user.username %>,</h1>

<h2 class="my-pokemon">Please choose the Pokemon you would like to battle with from your team</h2>


<div class="container d-flex justify-content-around mt-2">

<% current_user.user_pokemons.each do |pair| %>

<% @pokemon = pair.pokemon %>
<% @type = @pokemon.kind_of.downcase %>


<div class="cust-cards d-flex flex-column">

	<%= simple_form_for(@battle) do |f| %>

	  <%= f.hidden_field :pokemon_id, value: @pokemon.id %>
	  <%= f.hidden_field :enemy_id, value: params[:enemy_id] %>

	  <%= f.button :submit, class: "choose-btn", value: "Choose" %>

	<% end %>

	<figure class="card card--<%= @type%>">

		<div class="card__image-container">
			<img src="<%= @pokemon.picture %>" alt="Eevee" class="card__image">
		</div>

		<figcaption class="card__caption">
			<h1 class="card__name"><%= @pokemon.name %></h1>

			<h3 class="card__type">
				<%= @pokemon.kind_of %>
			</h3>

			<table class="card__stats">
				<tbody>
					<tr>
						<th>HP</th>
						<td><%= @pokemon.hp %></td>
					</tr>
					<tr>
						<th>Attack</th>
						<td><%= @pokemon.attack %></td>
					</tr>

					<tr>
						<th>Defense</th>
						<td><%= @pokemon.defense %></td>
					</tr>

					<tr>
						<th>Special Attack</th>
						<td><%= @pokemon.special_attack %></td>
					</tr>
					<tr>
						<th>Special Defense</th>
						<td><%= @pokemon.special_defense%></td>
					</tr>
					<tr>
						<th>Speed</th>
						<td><%= @pokemon.speed %></td>
					</tr>
				</tbody>
			</table>
		</figcaption>
	</figure>
</div>
<% end %>
</div>

app/views/battles/show.html.erb
<div class="final-message"></div>


<h2 class="mt-0">This is your time to shine!</h2>


<div class="container d-flex justify-content-around align-items-center mt-3">
  <% me = @battle.user %>
  <% @pokemon = Pokemon.find(params[:pokemon_id]) %>
  <% @type = @pokemon.kind_of.downcase %>

  <%@moves = @pokemon.moves.sample(2) %>

  <div class="d-flex flex-column">

    <div class="mt-3">
      <h2><%= me.username %></h2>
      <div class="mt-3">
        <h6><strong>Health:</strong></h6>
        <progress id="health-player-one" value="100" max="100" ></progress>
      </div>
    </div>
    <div class="cust-cards">
      <figure class="card card--<%= @type%>">
        <div class="card__image-container">
          <img src="<%= @pokemon.picture %>" alt="Eevee" class="card__image">
        </div>

        <figcaption class="card__caption">
          <h1 class="card__name mt-2" data-hp="<%= @pokemon.hp %>" id="pokemon-one-name"><%= @pokemon.name %></h1>

          <h3 class="card__type">
            <%= @pokemon.kind_of %>
          </h3>

          <table class="card__stats">
            <tbody>
              <tr>
                <th class="header mr-1">Available Moves</button></th>
                <td>Value</td>
              </tr>

              <% @moves.each do |move| %>
              <tr>
                <th><button class="btn btn--border player-one" data-movename="<%= move["name"] %>" data-movevalue="<%= move["power"] %>"><%= move["name"].upcase %></button></th>

                <td><%= move["power"] %></td>
            </tr>
            <% end %>
          </tbody></table>
        </figcaption>
      </figure>
    </div>
  </div>

  <h1>VS</h1>

  <% you = User.find(@battle.enemy_id) %>

<!--   <%# if session[:enemy_poke_id].present? %>
    <%# @enemy_pokemon = Pokemon.find(session[:enemy_poke_id].to_i)  %>
  <%# else %>
    <%# @enemy_pokemon = you.pokemons.sample %>
    <%# session[:enemy_poke_id] = @enemy_pokemon.id %>
  <%# end %> -->

  <% @enemy_pokemon = you.pokemons.sample %>

  <% @type = @enemy_pokemon.kind_of.downcase %>

  <% @enemy_moves = @enemy_pokemon.moves.sample(2) %>

<div class="d-flex flex-column">
<div class="mt-3">
      <h2><%= you.username %></h2>
      <div class="mt-3">
        <h6><strong>Health:</strong></h6>
        <progress id="health-player-two" value="100" max="100" ></progress>
      </div>
</div>
    <div class="cust-cards">
      <figure class="card card--<%= @type%>">
        <div class="card__image-container">
          <img src="<%= @enemy_pokemon.picture %>" alt="Eevee" class="card__image">
        </div>

        <figcaption class="card__caption">

          <h1 class="card__name mt-2" data-hp="<%= @enemy_pokemon.hp %>" data-moveone="<%= @enemy_moves[0]["power"] %>" data-movetwo="<%= @enemy_moves[1]["power"] %>" id="pokemon-two-name"><%= @enemy_pokemon.name %></h1>

          <h3 class="card__type">
            <%= @enemy_pokemon.kind_of %>
          </h3>

          <table class="card__stats">

            <ul>
              <li class="moves-list m-3"> <strong>Available Moves</strong> </li>
              <% @enemy_moves.each do |move| %>
              <li class="moves mt-3 mr-5 player-two" data-movename="<%= move["name"] %>" data-movevalue="<%= move["power"] %>" data-hp="<%= @pokemon.hp %>"><%= move["name"]%></li>
              <% end %>
            </ul>
            <!-- <tbody>
              <tr>
                <th class="header">Available Moves</th>
              </tr>
                <%# @sample_moves.each do |move| %>
                <tr>
                  <th class="btn btn--border"><%#= move["name"] %></th>
              </tr>
              <% #end %>

          </tbody></table> -->
        </figcaption>
      </figure>
    </div>
  </div>
</div>



<%=  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>PokeBnR</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>

    <% if !@disable_nav %>
      <%= render 'shared/navbar'%>
    <% end %>
    <%= render 'shared/flashes' %>
    <div>
      <div class="page-cover"></div>
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="container my-5 d-inline-flex rounded" style="background-color:white; opacity: 0.9; align-self: center;">
	<div class="row align-items-center justify-content-center p-5">
    	<div class="col-md-5" >
  			<%= image_tag "oak.png", style:"max-block-size:fit-content", class: "" %>
    	</div>
    	<div class="col-md-7 text-center p-4 rounded">
      		<p>Hey there! Welcome to the world of pokémon! Are you a <span style="background-color:blue; padding: 5px; border-radius: 20%; color:white;">boy</span> or a <span style="background-color:red; padding: 5px; border-radius: 20%; color:white;">girl</span>?</p>
          <br>
          <p>My name is Professor Oak! This world is inhabited by creatures called pokémon! For some people, pokémon are pets. Others use them for fights. Myself...I study pokémon as a profession.</p>
      		<br>
      		<p>PokeBnR is a game involving creatures called “pokémon” and “trainers.” Pokémon trainers can choose pokemon and use them to battle other pokemon and trainers.</p><br>
      		<p>The pokémon themselves are various, having different appearances, names, powers, potentials, weaknesses, and personalities and any good trainer knows that you can't learn unless you play the game. Pokemon can evolve, grow stronger, and lead the trainer to greater pursuits and glory.</p>
      		<br>
      		<p>To learn even more about Pokemon, click <%= link_to "here", "https://www.livemint.com/Sundayapp/Z7zHxltyWtFNzcoXPZAbjI/A-brief-history-of-Pokmon.html", :target => "_blank"  %>.To begin playing and start building your team: </p><br>
          <a href="/users/sign_up" class="btn" id="add-btn" style="color:white;">Sign Up</a>
    	</div>
    </div>
</div>

app/views/pages/landing.html.erb
  <div class="banner">

    <div class="container">

      <div class="content">
        <%= image_tag "pokemon_logo.png", alt: "alttext", class: "pokemon-logo"%>
        <p class="italic">Are you ready to catch 'em all?</p>
      </div>

      <div class="button-container d-flex justify-content-center flex-wrap flex-column">
        <%# path = current_user ? user_path(current_user) : new_user_session_path %>
        <%= link_to "Absolutely!", home_path, class: "cus-btn btn-1"  %>
      </div>
    </div>

  </div>

app/views/pokemons/index.html.erb
<div class="container">
<h1 class="mt-4" style="margin: 15px auto;"><strong>POKEDEX</strong></h1>

<div class="search__container">
  <%= form_tag pokemons_path, method: :get, class: "mt-0" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "search__input",
    placeholder: "Search for a pokemon, type, move" %>
  <% submit_tag %>
  <% end %>

</div>

<div class="cards-list" >

    <% @pokemons.each do |pokemon|  %>

      <div class="cust-card 1 pokemon">
        <%= link_to pokemon_path(pokemon) do %>
          <div class="card_image m-1" style="background-image: url(<%= pokemon.picture %>)"></div>
          <div class="card_title title-black">
            <p ><%= pokemon.name %></p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>




<div class="pagination">
  <% if params[:query].present? %>
  <% else %>
  <%= will_paginate @pokemons, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  <% end %>
</div>
</div>

app/views/pokemons/show.html.erb
<div class="container p-3 my-5 rounded" style="background-color: white; min-height: 70vh;">
  <div class="row justify-content-center">
    <div class="col-md-1">
      <div class="hero-text">
        <%= link_to "<", pokemons_path, class: "btn btn-success go" %>
      </div>
    </div>
    <div class="col-md-9">
      <div>
        <h2><%= @pokemon.number %></h2>
      </div>
    </div>
    <div class="col-md-2">
      <div class="hero-text">
        <div class="addition">
          <% if current_user %>
          <% if current_user.user_pokemons.length < 3 %>
          <%= simple_form_for([current_user, UserPokemon.new]) do |f| %>
          <%= f.hidden_field :pokemon_id, value: params[:id].to_i %>
          <%= f.button :submit, id: "add-btn", value: "Add to Team", style: "color:white" %>
          <% end %>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-md-12 hero-text">
      <h2><%= @pokemon.name %></h2>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col" style="text-align: -webkit-center;">
      <p class="card--<%=@pokemon.kind_of.downcase%> rounded" style="width:10%;color:white"><%= @pokemon.kind_of %></p>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-md-6">
      <p class="descriptive"><%= @pokemon.description %></p>
      <div class="hero-info">
          <!-- <h2>Info</h2>
          <ul>
            <li><span class="cat"><p>Type</p></span><span class="stats"><%= @pokemon.kind_of %></span></li>
            <li><span class="cat">Health</span><span class="stats"><%= @pokemon.hp %></span></li>
          </ul> -->
        </div>
      </div>
      <div class="col-md-6">
        <div class="hero-image" style="background-image: url(<%= @pokemon.picture %>); height: 100%;">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_form.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_area :details, class: 'form-control' %>
  </div>

  <% unless f.object.new_record? %>
    <div class="checkbox">
      <label>
        <%= f.check_box :completed %> Completed
      </label>
    </div>
  <% end %>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/shared/_from.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_area :details, class: 'form-control' %>
  </div>

  <% unless f.object.new_record? %>
    <div class="checkbox">
      <label>
        <%= f.check_box :completed %> Completed
      </label>
    </div>
  <% end %>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="page">
  <nav class="menu">
    <ul class="menu__list">
        <%= image_tag "pokeball.png", id: "logo" %>

        <% if current_user %>
        <li class="menu__group"><%= link_to "Community", users_path, class: "menu__link" %></li>
        <li class="menu__group"><%= link_to "Pokemon", pokemons_path, class: "menu__link" %></li>
        <li class="menu__group"><%= link_to "My Pokemon", user_path(current_user), class: "menu__link" %></li>
        <li class="menu__group"><%= link_to "Sign Out", destroy_user_session_path, method: :delete,  class: "menu__link" %></li>
        <% if current_user.photo.attached? %>

          <li class="menu__group"><%= cl_image_tag(current_user.photo.key, :transformation=>[
                {:width=>400, :height=>400, :gravity=>"auto", :radius=>"max", :crop=>"crop"},
                {:width=>40, :crop=>"scale"}
                ], id:"uservatar", style: "border-radius:50%") %></li>
        <% end %>
    
        <% else %>
        <li class="menu__group"><%= link_to "Community", users_path, class: "menu__link" %></li>
        <li class="menu__group"><%= link_to "Pokemon", pokemons_path, class: "menu__link" %></li>
        <li class="menu__group"><%= link_to "My Pokemon", new_user_session_path, class: "menu__link" %></li>
        <li class="menu__group"><%= link_to "Sign Up", new_user_registration_path, class: "menu__link" %></li>
        <% end %>

        </li>
    </ul>
  </nav>
</div>

app/views/user_pokemons/_form.html.erb
<%= simple_form_for([current_user, @user_pokemon]) do |f| %>
  <%= f.input :nickname, :label => "Give it a Nickname?"%>
  <%= f.association :pokemon, as: :select %>
  <%= f.button :submit %>
<% end %>

app/views/user_pokemons/new.html.erb
<div class="container text-center m-3 mx-auto rounded">
	<%= render 'form', user_pokemon: @user_pokemon %>
</div>

app/views/users/index.html.erb
<div class="container justify-content-center">
<h1 class="header-index"><strong>INDIGO LEAGUE</strong></h1>

<!-- <div class="sort_by">
  <div class="rdlLb"><span class="jQgLo">Sort By</span></div>
  <select name="price_max" id="forsale_price_max" data-section="for-sale" data-selectboxit="false">
            <option value="">Rank</option>

    <option value="scroll" data-condensed="10k">Scroll</option>
    <option value="Ascending" data-condensed="20k">Ascending</option>
    <option value="Descending" data-condensed="30k">Descending</option>
  </select>
  <select name="price_max" id="forsale_price_max" data-section="for-sale" data-selectboxit="false">
            <option value="">Energy</option>

    <option value="scroll" data-condensed="Value">£10,000</option>
    <option value="Value" data-condensed="Value">£20,000</option>
    <option value="Value" data-condensed="Value">£30,000</option>
    <option value="Value" data-condensed="Value">£40,000</option>
  </select>
  <select name="price_max" id="forsale_price_max" data-section="for-sale" data-selectboxit="false">
            <option value="">No max</option>

    <option value="scroll" data-condensed="Value">£10,000</option>
    <option value="value" data-condensed="Value">£20,000</option>
    <option value="Value" data-condensed="Value">£30,000</option>
    <option value="Value" data-condensed="Value">£40,000</option>
  </select>
</div> -->

<div class="search__container">
  <%= form_tag users_path, method: :get, class: "mt-0" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "search__input",
    placeholder: "Search for a user" %>
  <% submit_tag %>
  <% end %>

</div>


<!-- Sort by: <%#= link_to "Rank desc", users_path(sort: 'rank_desc') %> |  <%#= link_to "Rank asc", users_path(sort: 'rank_asc') %>
 -->

  <% counter = 0 %>
  <div class="card-product small">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-md-1">
          <div class="division_ranks">
            <h5><strong>RANK</strong></h5>
          </div>
        </div>
        <div class="col-md-1">
          <h5><strong>AVATAR</strong></h5>
        </div>
        <div class="col-md-2 flex-nowrap">
            <h5><strong>TRAINER NAME</strong></h5>
        </div>
        <div class="col-md-5">
          <h5><strong>CURRENT TEAM</strong></h5>
        </div>
        <div class="col-md-1">
            <h5><strong>BATTLES FOUGHT</strong></h5>
        </div>
        <div class="col-md-1">
            <h5><strong>WIN RATE</strong></h5>
        </div>
        <div class="col-md-1">
          <h5><strong>BATTLE!</strong></h5>
        </div>
      </div>
    </div>
  </div>


  <%@users.each do |user| %>
  <div class="card-product">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-md-1">
          <div class="division_ranks">
            <h5>#<%= counter+=1 %></h5>
          </div>
        </div>
        <div class="col-md-1">
          <% if user.photo.attached? %>
            <%= cl_image_tag(user.photo.key, :transformation=>[
              {:width=>400, :height=>400, :gravity=>"auto", :radius=>"max", :crop=>"crop"},
              {:width=>40, :crop=>"scale"}
              ], class:"avatar") %>
          <% else %>
            <img class="avatar " src="https://vignette.wikia.nocookie.net/295e578f-a7d1-4240-bc80-303bcfd62dc8">
          <% end %>
        </div>
        <div class="col-md-2 warrior-name">
          <td class="align-middle">
            <%=link_to user.username.capitalize, user_path(user) %>
          </td>
        </div>
        <div class="col-md-5 card-product-infos" style="justify-content:space-evenly">
          <%user.user_pokemons.each do |pair| %>
          <% @pokemon = pair.pokemon %>
          <div>
            <img src="<%= @pokemon.picture %>">
            <div class="pokemon-box-width">
              <p><%= @pokemon.name %></p>
            </div>
          </div>
          <% end %>
        </div>
        <div class="col-md-1">

            <p><%= user.battles_fought %></p>

        </div>
        <div class="col-md-1">
          <div>
            <p><%= user.battles_fought == 0 ? 0 : user.battles_won / user.battles_fought * 100 %>%</p>
          </div>
        </div>
        <div class="col-md-1">

         <%= link_to "Battle", new_battle_path(user_id: current_user, enemy_id: user.id), class: "battle-btn"  %>

        </div>
      </div>
    </div>
  </div>
  <% end %>
  </div>

app/views/users/show.html.erb
  <div class="container p-3 my-5 rounded" style="background-color: white;">
    <div class="row justify-content-center">
      <div class="col-md-12">
        <h1 class="username" style="color: black;"><strong><%= @user.username.capitalize %></strong></h1>
      </div>
    </div>
    <div class="row justify-content-center">
      <% if @user != current_user %>
        <%= link_to "Battle!", new_battle_path(user_id: current_user, enemy_id: @user.id), id:"add-btn", class: "btn" %>
      <% else %>
        <h2 class="my-pokemon">My Pokemon</h2>
      <% end %>
    </div>


    <% @user.user_pokemons.each do |pair| %>

      <% @pokemon = pair.pokemon %>
      <% @type = @pokemon.kind_of.downcase %>


      <div class="cust-cards">
        <figure class="card card--<%= @type%>">
          <div class="card__image-container">
            <img src="<%= @pokemon.picture %>" alt="Eevee" class="card__image">
          </div>

          <figcaption class="card__caption">
            <h1 class="card__name"><%= @pokemon.name %></h1>

            <h3 class="card__type">
              <%= @pokemon.kind_of %>
            </h3>

            <table class="card__stats">
              <tbody><tr>
                <th>HP</th>
                <td><%= @pokemon.hp %></td>
              </tr>
              <tr>
                <th>Attack</th>
                <td><%= @pokemon.attack %></td>
              </tr>

              <tr>
                <th>Defense</th>
                <td><%= @pokemon.defense %></td>
              </tr>

              <tr>
                <th>Special Attack</th>
                <td><%= @pokemon.special_attack %></td>
              </tr>
              <tr>
                <th>Special Defense</th>
                <td><%= @pokemon.special_defense%></td>
              </tr>
              <tr>
                <th>Speed</th>
                <td><%= @pokemon.speed %></td>
              </tr>
            </tbody></table>

          </figcaption>
          <% if @user == current_user %>
            <%= link_to "Remove", user_user_pokemon_path(current_user, pair),method: :delete,class: "btn-success btn float-right"%> 
          <% end %>
        </figure>
      </div>
    <% end %>
    <% if @user.user_pokemons.length < 3 %>
      <div class="cust-cards">
        <figure class="btn text-center" id="add-btn">
          <%= link_to "Add a Pokemon", pokemons_path, style:"color:white;" %>
        </figure>
      </div>
    <% end %>
  </div>
</div>